services:
  - type: web
    name: matibashoe
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn Matibashoe.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: matibashoe.onrender.com,*.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: matibashoe-db
          property: connectionString
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        value: blessingbraelly@gmail.com
      - key: EMAIL_HOST_PASSWORD
        sync: false

databases:
  - name: matibashoe-db
    plan: free
    databaseName: matibashoe
    user: matibashoe_user

